# Generated by Django 4.1.4 on 2022-12-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='undMedida',
            field=models.CharField(blank=True, choices=[('KG', 'Kilograma'), ('MT', 'Metros'), ('CM', 'Centimetros'), ('MG', 'Miligramas'), ('L', 'Litros')], max_length=2, null=True, verbose_name='Unidade de medida'),
        ),
    ]
